package com.example.inventory.service;

import com.example.inventory.model.Product;
import com.example.inventory.repository.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Implementación de la Lógica de Negocio.
 */
@Service
public class ProductServiceImpl implements ProductService {

    private final ProductRepository productRepository;

    // Inyección de dependencias por constructor
    @Autowired
    public ProductServiceImpl(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }


    //  Guardar un nuevo producto en PostgreSQL con SKU generado automáticamente
    @Override
    public Product saveProduct(Product product) {
        // Si el cliente no envió SKU o envió texto vacío, generamos un SKU estandarizado
        if (product.getSku() == null || product.getSku().trim().isEmpty()) {
            String autoGeneratedSku = "SKU-" + (int)(Math.random() * 900000 + 100000); // Ej: SKU-849201
            product.setSku(autoGeneratedSku);
        } else {
            product.setSku(product.getSku().trim().toUpperCase());
        }
        return productRepository.save(product);
    }
    //Obtener la lista completa de productos
    @Override
    public List<Product> getAllProducts() {
        return productRepository.findAll();
    }

    //  Buscar un producto por su ID
    @Override
    public Product getProductById(Long id) {
        return productRepository.findById(id).orElse(null);
    }

    //  Buscar un producto existente y modificar sus datos
    @Override
    public Product updateProduct(Long id, Product productDetails) {
        Product existingProduct = productRepository.findById(id).orElse(null);
        if (existingProduct != null) {
            existingProduct.setSku(productDetails.getSku());
            existingProduct.setName(productDetails.getName());
            existingProduct.setPrice(productDetails.getPrice());
            existingProduct.setStockQuantity(productDetails.getStockQuantity());
            return productRepository.save(existingProduct);
        }
        return null;
    }

    //  Borrar un producto de PostgreSQL por su ID
    @Override
    public void deleteProduct(Long id) {
        productRepository.deleteById(id);
    }
}