spring.application.name=inventory


# Conexión a tu PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Indicar a Hibernate que se conecte a la tabla existente sin sobrescribirla
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar consultas SQL en la consola para ver qué hace Hibernate
spring.jpa.show-sql=true